/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practicapeajes.IU;

import java.util.List;
import practicapeajes.Objetos.Multa;
import practicapeajes.Sistema.SistemaPeaje;
import practicapeajes.Usuarios.Conductor;

/**
 *
 * @author DavidArevaloRey
 */
public class IU_Conductor extends javax.swing.JFrame {
    private Conductor c;
    /** Creates new form IU_Conductor */
    public IU_Conductor(Conductor c) {
        initComponents();
        this.c = c;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consular_multas = new javax.swing.JButton();
        consultar_multas_pendientes = new javax.swing.JButton();
        Pagar_Multas = new javax.swing.JButton();
        matricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ventana = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setTitle("Interfaz_Conductor");

        consular_multas.setText("Consultar todas las multas");
        consular_multas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consular_multasActionPerformed(evt);
            }
        });

        consultar_multas_pendientes.setText("Consultar multas pendientes");
        consultar_multas_pendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_multas_pendientesActionPerformed(evt);
            }
        });

        Pagar_Multas.setText("Pagar multas");
        Pagar_Multas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pagar_MultasActionPerformed(evt);
            }
        });

        matricula.setText("Matricula");

        Ventana.setEditable(false);
        Ventana.setColumns(20);
        Ventana.setRows(5);
        jScrollPane1.setViewportView(Ventana);

        jLabel1.setText("IU_Conductor");

        id.setText("Identificador");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(consultar_multas_pendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                .addComponent(Pagar_Multas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consular_multas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(consular_multas, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(consultar_multas_pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Pagar_Multas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pagar_MultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pagar_MultasActionPerformed
        // TODO add your handling code here:
        String m = matricula.getText();
        String idT = id.getText();
        if(m.isEmpty()){
            Ventana.setText("Introduza una matricula valida");
            return;
        }
        if(idT.isEmpty()){
        Ventana.setText("Introduza una identificacion valida");
            return;

        }
        
        int i = Integer.parseInt(idT);
        boolean b = c.pagarMulta(m, i);
        
        if(b){
                Ventana.setText("Multa pagada de forma exitosa del vehiculo " + m + " cuyo identificador es: " + idT);

        }else{
                Ventana.setText("Esa multa no se encontro");

        }
        
    }//GEN-LAST:event_Pagar_MultasActionPerformed

    private void consular_multasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consular_multasActionPerformed
        String m = matricula.getText();
        if(!m.isEmpty()){
            List<Multa> multas = c.verMultas(m);
            if(!multas.isEmpty()){
                StringBuilder sb = new StringBuilder("Multas: \n");
                for(Multa ma: multas){
                sb.append(ma.toString()).append("\n");
                }
                Ventana.setText(sb.toString());
                
            }else{
            
            Ventana.setText("No hay matriculas en el registro");

            }
        
        
        }else{
            Ventana.setText("Introduce una marticula valida");
        
        }
    }//GEN-LAST:event_consular_multasActionPerformed

    private void consultar_multas_pendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_multas_pendientesActionPerformed

        
                String m = matricula.getText();
        if(!m.isEmpty()){
            List<Multa> multas = c.verMultasPendientes(m);
            if(!multas.isEmpty()){
                StringBuilder sb = new StringBuilder("Multas pendientes: \n");
                for(Multa ma: multas){
                sb.append(ma.toString()).append("\n");
                }
                Ventana.setText(sb.toString());
                
            }else{
            
            Ventana.setText("No hay matriculas en el registro");

            }
        
        
        }else{
            Ventana.setText("Introduce una marticula valida");
        
        }
    }//GEN-LAST:event_consultar_multas_pendientesActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SistemaPeaje sistemaPeaje = new SistemaPeaje();
                Conductor c = new Conductor(sistemaPeaje);
                new IU_Conductor(c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pagar_Multas;
    private javax.swing.JTextArea Ventana;
    private javax.swing.JButton consular_multas;
    private javax.swing.JButton consultar_multas_pendientes;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matricula;
    // End of variables declaration//GEN-END:variables

}
