/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicapeajes.IU;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import practicapeajes.Objetos.Multa;
import practicapeajes.Objetos.Ticket;
import practicapeajes.Objetos.Vehiculo;
import practicapeajes.Sistema.SistemaPeaje;
import practicapeajes.Usuarios.Operario;

/**
 *
 * @author DavidArevaloRey
 */
public class IU_Operario extends javax.swing.JFrame {
    private Operario operarioA;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    /**
     * Creates new form IU_Operario
     */
    public IU_Operario(Operario operario) {
        initComponents();
        this.operarioA = operario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Registrar_entrada = new javax.swing.JButton();
        Registrar_salida = new javax.swing.JButton();
        matricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pantalla = new javax.swing.JTextArea();
        Peso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        consultar_Peaje = new javax.swing.JButton();
        Generar_tickets = new javax.swing.JButton();
        Consultar_abonadas = new javax.swing.JButton();
        consultar_pendientes = new javax.swing.JButton();

        setTitle("Interfaz_Operador");

        jLabel1.setText("IU Operario");

        Registrar_entrada.setText("Registrar entrada");
        Registrar_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_entradaActionPerformed(evt);
            }
        });

        Registrar_salida.setText("Registrar salida");
        Registrar_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_salidaActionPerformed(evt);
            }
        });

        matricula.setText("Introducir matricula");

        Pantalla.setColumns(20);
        Pantalla.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        Pantalla.setRows(5);
        Pantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(Pantalla);

        Peso.setText("Introducir peso");
        Peso.setToolTipText("");

        jLabel2.setText("Ingrese el peso cuando desee registrar la salida de un vehiculo junto a su matricula");

        consultar_Peaje.setText("Consultar peaje");
        consultar_Peaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_PeajeActionPerformed(evt);
            }
        });

        Generar_tickets.setText("Generar ticket de peaje");
        Generar_tickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_ticketsActionPerformed(evt);
            }
        });

        Consultar_abonadas.setText("Consultar multas abonadas");
        Consultar_abonadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_abonadasActionPerformed(evt);
            }
        });

        consultar_pendientes.setText("Consultar multas pendientes");
        consultar_pendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_pendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultar_Peaje, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(Registrar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Registrar_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(783, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Consultar_abonadas, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                        .addComponent(Generar_tickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultar_pendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consultar_abonadas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Generar_tickets, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(consultar_pendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Registrar_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Registrar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consultar_Peaje, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Registrar_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_entradaActionPerformed
        // TODO add your handling code here:
        String matri = matricula.getText();
        LocalDateTime fechaEntrada = LocalDateTime.now();
        if(matri.isEmpty()){
            Pantalla.setText("Introduza una matricula valida");
            return;
        }

        operarioA.registrarEntrada(matri, fechaEntrada);
        Pantalla.setText("Entrada registrada con exito del vehiculo con matricula " + matri );
        

        
    }//GEN-LAST:event_Registrar_entradaActionPerformed

    private void Registrar_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_salidaActionPerformed
        String matri = matricula.getText();
        String tamano = Peso.getText();
      
        
        if(matri.isEmpty()){
            Pantalla.setText("Introduza una matricula valida");
            return;
        }
        
        if(tamano.isEmpty()){
            Pantalla.setText("Introduza un tamanyo valido");
            return;
        }
        operarioA.registrarSalida(matri, java.time.LocalDateTime.now(), Double.parseDouble(tamano));
        Pantalla.setText("Salida registrada con exito del vehiculo con matricula " + matri + " cuyo tamanyo es: " + tamano + " m^(2)");
        
    }//GEN-LAST:event_Registrar_salidaActionPerformed

    private void consultar_PeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_PeajeActionPerformed
        // TODO add your handling code here:
         String matri = matricula.getText();
                
         if(matri.isEmpty()){
            Pantalla.setText("Introduza una matricula valida");
            return;
        }
        List<Ticket> tickets = operarioA.verTickets(matri);
        if(tickets.isEmpty()){
            Pantalla.setText("Lista de tickets vacia");
            return;
        }
                    
             StringBuilder sb = new StringBuilder();
             for(Ticket t: tickets){
             sb.append(t.toString()).append("\n");
             
             }
            Pantalla.setText(sb.toString());
        

                

    }//GEN-LAST:event_consultar_PeajeActionPerformed

    private void consultar_pendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_pendientesActionPerformed
        // TODO add your handling code here:
                String matri = matricula.getText();
        if(matri.isEmpty()){
            Pantalla.setText("Introduza una matricula valida");
            return;
        }

        
            List<Multa> multas = operarioA.verMultasPendientes(matri);
        if(multas.isEmpty()){
            Pantalla.setText("Lista de multas pendientes vacia");
            return;
        }

             StringBuilder sb = new StringBuilder();
             for(Multa t: multas){
             sb.append(t.toString()).append("\n");
             }
            Pantalla.setText(sb.toString());
        

        
    }//GEN-LAST:event_consultar_pendientesActionPerformed

    private void Generar_ticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_ticketsActionPerformed
        String matri = matricula.getText();
        if(matri.isEmpty()){
            Pantalla.setText("Introduza una matricula valida");
            return;
        }

       
           Ticket t = operarioA.generarTicket(matri);
           if(t != null){
                       Pantalla.setText("Se ha generado el ticket. \n");
                       Pantalla.append(t.toString());
                       operarioA.exportarHistorial(matri);

           }else{
               Pantalla.setText("No se ha generado el ticket. \n");

           
           }
            
        
    }//GEN-LAST:event_Generar_ticketsActionPerformed

    private void Consultar_abonadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_abonadasActionPerformed
        // TODO add your handling code here:
        String matri = matricula.getText();
        if(matri.isEmpty()){
            Pantalla.setText("Introduza una matricula valida");
            return;
        }

        
            List<Multa> multas = operarioA.verMultasPagadas(matri);
            
            if(multas.isEmpty()){
            Pantalla.setText("Lista de multas abonadas vacia");
            return;
        }

             StringBuilder sb = new StringBuilder();
             for(Multa t: multas){
             sb.append(t.toString()).append("\n");
             Pantalla.setText(sb.toString());
             }
            
        
    }//GEN-LAST:event_Consultar_abonadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Operario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SistemaPeaje sistemaPeaje = new SistemaPeaje();
               practicapeajes.Usuarios.Operario operarioActual = new practicapeajes.Usuarios.Operario(sistemaPeaje);
               
                new IU_Operario(operarioActual).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar_abonadas;
    private javax.swing.JButton Generar_tickets;
    private javax.swing.JTextArea Pantalla;
    private javax.swing.JTextField Peso;
    private javax.swing.JButton Registrar_entrada;
    private javax.swing.JButton Registrar_salida;
    private javax.swing.JButton consultar_Peaje;
    private javax.swing.JButton consultar_pendientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matricula;
    // End of variables declaration//GEN-END:variables
}
